trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ci/cd.yml
      - iac

pool:
  vmImage: ubuntu-20.04

variables:
  environment: prod

parameters:
  - name: environments
    type: object
    default:
      - dev
      - stg
      - prod

stages:
  - stage: release_${{ variables.environment }}
    displayName: Release (${{ variables.environment }})
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - ${{ each environment in parameters.environments }}:
          - deployment: create_${{ environment }}
            displayName: Create ${{ environment }}
            environment: ${{ environment }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: AzureCLI@2
                      displayName: Create deployment
                      inputs:
                        azureSubscription: sp-landingzones-test-01
                        scriptType: pscore
                        scriptPath: iac/deploy.ps1
                        arguments: ${{ environment }} create
