trigger:
  branches:
    include:
      - main
  paths:
    include:
      - deploy
      - iac
pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription-test: subconnect
  workingDirectory: iac

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: iac
        displayName: Validate infrastructure
        steps:
          - task: AzurePowerShell@5
            displayName: test
            inputs:
              azureSubscription: $(azureSubscription-test)
              scriptPath: $(workingDirectory)/validate.ps1
              scriptArguments: test
              workingDirectory: $(workingDirectory)
              azurePowerShellVersion: latestVersion
              pwsh: true

  - stage: test
    displayName: Deploy to test
    dependsOn: build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: iac
        displayName: Deploy infrastructure
        environment: test
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: $(azureSubscription-test)
                    scriptPath: $(workingDirectory)/deploy.ps1
                    scriptArguments: test
                    workingDirectory: $(workingDirectory)
                    azurePowerShellVersion: latestVersion
                    pwsh: true