name: 'Func test'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 3 * * *'

env:
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}  
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  TFSTATE_STORAGE :  ${{ vars.TFSTATE_STORAGE }}
  AZURE_FUNCTIONAPP_NAME: 'func-x-analytics-dev-westeurope-01'

permissions:
  contents: write
  pages: write
  id-token: write  

jobs:
  func_build:
    name: 'Func build'
    runs-on: [ self-hosted, 'Linux']
    environment: ${{ matrix.environment }}
    strategy: 
      fail-fast: false
      matrix:
          environment:
              - dev
              #- utv

    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/func

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Python version
      uses: actions/setup-python@v5 #-- setup python on runner
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: | #-- 'run' is used to run commands on environment
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt #-- run the file of requirements

    - name: Zip artifact for deployment 
      run: |
        tar cvf release.zip ./
        ls

    - name: Upload artifact for deployment job 
      uses: actions/upload-artifact@v3 #-- upload the project to be deployed
      with:
        name: python-app
        path: |
            func/release.zip
    # !venv/

  func_deploy:
    name: 'Func Deploy'
    runs-on: [ self-hosted, 'Linux']
    strategy: 
      fail-fast: false
      matrix:
          environment:
              - dev
    environment: ${{ matrix.environment }}
    needs: [func_build]
    if: github.ref == 'refs/heads/main' && github.event_name != 'schedule'

    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/func

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app
    
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
    
    - name: 'Enabled'
      run: |
        az functionapp update \
        --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
        --resource-group 'rg-x-analytics-dev-westeurope-02' \
        --subscription ${{ env.ARM_SUBSCRIPTION_ID }} \
        --set publicNetworkAccess='Enabled'  

    - name: Unzip artifact for deployment
      run: tar xvf ../release.zip
        
    - name: 'Deploy to Azure Functions' 
      uses: Azure/functions-action@v1 #-- connect to cloud and deploy
      id: deploy-to-function
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './func'
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        
    - name: 'Disabled'
      run: |
        az functionapp update \
        --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
        --resource-group 'rg-x-analytics-dev-westeurope-02' \
        --subscription ${{ env.ARM_SUBSCRIPTION_ID }} \
        --set publicNetworkAccess='Disabled'
