pool:
  vmImage: ubuntu-22.04

stages:
  - stage: release
    displayName: Release
    jobs:
      - deployment: deploy
        displayName: Deploy
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: Create deployment
                  inputs:
                    azureSubscription: sp-opsgenie-prod
                    scriptType: pscore
                    scriptPath: scripts/pipelineFail.ps1

                - task: AzureCLI@2
                  condition: failed()
                  displayName: Check pipeline
                  inputs:
                    azureSubscription: sp-opsgenie-prod
                    scriptType: pscore
                    scriptPath: scripts/pipelineRerun.ps1
