trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ci/cd.yml
      - iac

pool:
  #vmImage: ubuntu-22.04
  name: vmmgmtX

parameters:
  - name: environments
    type: object
    default:
      - prod

schedules:
  - cron: "28 13 * * *"
    displayName: "automatiserad"
    always: true
    branches:
      include:
        - main

stages:
  - ${{ each environment in parameters.environments }}:
      - stage: release_${{ environment }}
        displayName: Release (${{ environment }})
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        jobs:
          - deployment: create_${{ environment }}
            displayName: Create (${{ environment }})
            ? ${{ if eq(variables['Build.CronSchedule.DisplayName'], 'automatiserad') }}
            : environment: schedule
            ${{ else }}:
              environment: ${{ environment }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: AzureCLI@2
                      displayName: Create deployment
                      inputs:
                        azureSubscription: sp-platform-01
                        scriptType: pscore
                        scriptPath: iac/deploy.ps1
                        arguments: ${{ environment }} create
