trigger:
  branches:
    include:
      - main
  paths:
    include:
      - runbooks

schedules:
  - cron: "45 7 * * *"
    #cron: '35 7 * * *'
    displayName: "automatiserad körning"
    always: true
    branches:
      include:
        - main

pool:
  vmImage: ubuntu-latest
  #name: vmmgmtprod01

variables:
  azureSubscription: sub-prod-01
  environment: runbooks
  workingDirectory: runbooks

stages:
  - stage: plan
    displayName: "Init + Plan"
    jobs:
      - job: plan
        displayName: Plan
        steps:
          - task: AzureCLI@2
            displayName: Set environment variables
            inputs:
              azureSubscription: ${{ variables.azureSubscription }}
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
                echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
          - script: |
              terraform init -input=false
              terraform plan -out=tfplan -input=false
            displayName: "Init + Plan"
            workingDirectory: runbooks
  - stage: apply
    displayName: "Init + Plan + Apply"
    jobs:
      - job: apply
        displayName: Apply
        steps:
          - task: AzureCLI@2
            displayName: Set environment variables
            inputs:
              azureSubscription: ${{ variables.azureSubscription }}
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
                echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
                echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
                echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
          - script: |
              terraform init -input=false
              terraform plan -out=tfplan -input=false
              terraform apply --auto-approve -input=false
            displayName: "Init + Plan + Apply"
            workingDirectory: runbooks
