trigger:
  branches:
    include:
      - main
  paths:
    include:
      - script
      - subscriptionsNames.txt

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: environments
    type: object
    default:
      - prod

stages:
  - ${{ each environment in parameters.environments }}:
      - stage: release_${{ environment }}
        displayName: Release (${{ environment }})
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        jobs:
          - deployment: create_${{ environment }}
            displayName: Create subscriptions
            environment: ${{ environment }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: AzureCLI@2
                      displayName: Create deployment
                      inputs:
                        azureSubscription: sp-subconnect-01
                        scriptType: pscore
                        scriptPath: script/script01.ps1