name: 'Func win runner'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 3 * * *'

env:
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID_DEV }}  
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID_DEV }} 
  ARM_TENANT_ID: ${{ vars.TENANT_ID_DEV }}
  TFSTATE_STORAGE :  ${{ vars.TFSTATE_STORAGE_DEV }}
  AZURE_FUNCTIONAPP_NAME: 'func-abc-dev-westeurope-01'

permissions:
  contents: write
  pages: write
  id-token: write  

jobs:
  func_build:
    name: 'Func build'
    runs-on: [ self-hosted, 'Windows']
    #environment: ${{ matrix.environment }}
    strategy: 
      fail-fast: false
      matrix:
          environment:
              - dev
              #- utv

    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/func

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Zip artifact for deployment 
      shell: pwsh
      run: |
        Compress-Archive -Path ./ -DestinationPath release.zip
        Get-ChildItem

    - name: Upload artifact for deployment job 
      uses: actions/upload-artifact@v3 #-- upload the project to be deployed
      with:
        name: python-app
        path: |
            func/release.zip

  func_deploy:
    name: 'Func Deploy'
    runs-on: [ self-hosted, 'Windows']
    strategy: 
      fail-fast: false
      matrix:
          environment:
              - dev
    environment: ${{ matrix.environment }}
    needs: [func_build]

    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/func

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app
    
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
    
    - name: UnZip artifact for deployment 
      shell: pwsh
      run: |
        Expand-Archive -LiteralPath ../release.zip -DestinationPath ./
        Get-ChildItem
        
    - name: 'Deploy to Azure Functions' 
      uses: Azure/functions-action@v1 #-- connect to cloud and deploy
      id: deploy-to-function
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './func'
        scm-do-build-during-deployment: true
        enable-oryx-build: true
