name: 'Deploy Azure Functions'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dev:
        default: true
        description: 'Deploy to dev environment'
        type: boolean

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  func_build_dev:
    name: 'Func Build for Dev'
    runs-on: [self-hosted, 'Windows']
    if: inputs.dev
    env:
      ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ vars.SUB_ID }}
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      AZURE_FUNCTIONAPP_NAME: 'funcrepublik001'
    strategy:
      fail-fast: false
    #   matrix:
    #     environment:
    #       - dev

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/deploy-func-python

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github
            deploy-func-python

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: List Files
        shell: pwsh
        run: Get-ChildItem

      - name: 'Resolve Project Dependencies Using Pip'
        shell: pwsh
        run: |
          Push-Location "./."
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          Pop-Location

      - name: Package Application
        shell: pwsh
        run: |
          Get-ChildItem
          New-Item -ItemType Directory -Name "ZIP-PACKED" -Path "../"
          Compress-Archive -Path ./* -DestinationPath ../ZIP-PACKED/release-test.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ./ZIP-PACKED/release-test.zip

  func_deploy_dev:
    name: 'Func Deploy to Dev'
    runs-on: [self-hosted, 'Windows']
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
    environment: ${{ matrix.environment }}
    env:
      ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ vars.SUB_ID }}
      ARM_TENANT_ID: ${{ vars.TENANT_ID }}
      AZURE_FUNCTIONAPP_NAME: 'funcrepublik001'
    needs: [func_build_dev]

    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/deploy-func-python

    steps:
      - name: New Folder
        shell: pwsh
        run: New-Item -ItemType Directory -Name "ZIP-DOWNLOAD" -Path "../"

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: python-app
          path: ./ZIP-DOWNLOAD

      - name: List Files
        shell: pwsh
        run: Get-ChildItem -Path "../"

      - name: Unpack Artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Name "ZIP-UNPACKED" -Path "../"
          Expand-Archive -LiteralPath ../ZIP-DOWNLOAD/release-test.zip -DestinationPath ../ZIP-UNPACKED -Force

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1.5.1
        id: deploy-to-function
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './ZIP-UNPACKED'
          scm-do-build-during-deployment: false
          enable-oryx-build: false
