name: Powershell Authentication

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SPOKE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
    connect:
      name: connect-azaccount
      runs-on: self-hosted
      defaults:
        run:
          shell: pwsh
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v2
          with:
            creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}' 
            enable-AzPSSession: true

        - name: Powershell
          shell: pwsh
          id: powershell
          run: |
            Get-AzContext
            Get-AzAccessToken
