trigger:
  branches:
    include:
      - main
  paths:
    include:
      - runbooks

schedules:
  - cron: 0 0 * * *
    branches:
      include:
        - main
    always: true

pool:
  #vmImage: ubuntu-latest
  name: vmmgmtprod01
variables:
  azureSubscription: sub-labb-01
  environment: prod
  workingDirectory: runbooks

steps:
  - task: AzureCLI@2
    displayName: Set environment variables
    inputs:
      azureSubscription: ${{ variables.azureSubscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
        Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
        Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
        Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
        Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
  - script: |
      terraform init -input=false
      terraform plan -out=tfplan -input=false
      terraform apply --auto-approve -input=false
    displayName: "Terraform"
    workingDirectory: runbooks
