name: 'azcopy raw daily'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * *'
permissions:
  id-token: write
  contents: read

env:
  AZCOPY_AUTO_LOGIN_TYPE: AZCLI
  AZURE_CLIENT_ID: ${{ vars.CLIENT_ID_DEV }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID_DEV }}
  AZURE_TENANT_ID: ${{ vars.TENANT_ID_DEV }}
  ARM_USE_OIDC: true
  AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_DEV }}
  AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_DEV }}
  DL_NAME: "stabcsatsdevweu01"
  BACKUP_ST_NAME: "stabcsatsdevweu10"
  BACKUP_SOURCE_FOLDER: "diaccadlsfsdev/dw/raw"
  BACKUP_DEST_FOLDER: "backup-datalake-raw-daily/dw/"

jobs:
  terraform_build_and_plan:
    name: 'AzCopy raw daily'
    runs-on: [self-hosted, linux]
    #environment: dev

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'

    - name: Set MY_DATE environment variable
      run:  echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Print MY_DATE
      run: echo ${{ env.MY_DATE }} 

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: AzCopy sync ${{env.DL_NAME}} to ${{env.BACKUP_ST_NAME}}
      run: | 
        azcopy_v10 sync 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_SOURCE_FOLDER}}' 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER}}' --recursive=true