name: 'azcopy delta monthly recovery file'

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        default: dev
        type: choice
        options:
          - dev
          - qua
          - prd
      recover-delta:
        default: true
        type: boolean
      date-delta: 
        default: "2024-06-26"
      folder-delta-source:
        default: "diaccadlsfsdev/dw/delta/NAV/customer_nav"
      folder-delta-destination:
        default: "restored-delta-files/dw/delta/NAV"
      recover-delta-latest:
        default: true
        type: boolean
      date-delta-lates: 
        default: "2024-06-26"
      folder-delta-latest-source:
        default: "diaccadlsfsdev/dw/delta_latest/NAV/customer_nav"
      folder-delta-latest-destination:
        default: "restored-delta-latest-files/dw/delta_latest/NAV/customer_nav"

permissions:
  id-token: write
  contents: read

env:
  AZCOPY_AUTO_LOGIN_TYPE: AZCLI
  ARM_USE_OIDC: true
  BACKUP_SOURCE_FOLDER: "${{ inputs.folder-delta-source }}"
  BACKUP_DEST_FOLDER: "${{ inputs.folder-delta-destination }}"
  BACKUP_SOURCE_FOLDER_2: "${{ inputs.folder-delta-latest-source }}"
  BACKUP_DEST_FOLDER_2: "${{ inputs.folder-delta-latest-destination }}"
  DL_NAME: "stabcde${{ inputs.env }}weu01"
  BACKUP_ST_NAME: "stabcde${{ inputs.env }}weu10"

jobs:
  az_copy_dev:
    name: 'AzCopy delta monthly (dev)'
    runs-on: [self-hosted, linux]
    if: ${{ inputs.env == 'dev' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'

    - name: Set MY_DATE environment variable
      id: my_date
      run: echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set TIMESTAMP environment variable
      id: timestamp
      run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
    
    - name: Print MY_DATE
      run: |
        echo MY_DATE: ${{ env.MY_DATE }}   
        echo TIMESTAMP: ${{ env.TIMESTAMP }} 

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.CLIENT_ID_DEV }}
        tenant-id: ${{ vars.TENANT_ID_DEV }}
        subscription-id: ${{ vars.SUBSCRIPTION_ID_DEV }}

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta
      if: inputs.recover-delta
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_DEV }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_DEV }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta }}/${{env.BACKUP_SOURCE_FOLDER}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER}}' --recursive=true

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta-latest
      if: inputs.recover-delta-latest
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_DEV }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_DEV }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta-lates }}/${{env.BACKUP_SOURCE_FOLDER_2}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER_2}}' --recursive=true
  
  az_copy_qua:
    name: 'AzCopy delta monthly (qua)'
    runs-on: [self-hosted, linux]
    if: ${{ inputs.env == 'qua' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'

    - name: Set MY_DATE environment variable
      id: my_date
      run: echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set TIMESTAMP environment variable
      id: timestamp
      run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
    
    - name: Print MY_DATE
      run: |
        echo MY_DATE: ${{ env.MY_DATE }}   
        echo TIMESTAMP: ${{ env.TIMESTAMP }} 

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.CLIENT_ID_QUA }}
        tenant-id: ${{ vars.TENANT_ID_QUA }}
        subscription-id: ${{ vars.SUBSCRIPTION_ID_QUA }}

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta
      if: inputs.recover-delta
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_QUA }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_QUA }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta }}/${{env.BACKUP_SOURCE_FOLDER}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER}}' --recursive=true

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta-latest
      if: inputs.recover-delta-latest
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_QUA }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_QUA }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta-lates }}/${{env.BACKUP_SOURCE_FOLDER_2}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER_2}}' --recursive=true
  
  az_copy_prd:
    name: 'AzCopy delta monthly (prd)'
    runs-on: [self-hosted, linux]
    if: ${{ inputs.env == 'prd' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'

    - name: Set MY_DATE environment variable
      id: my_date
      run: echo "MY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set TIMESTAMP environment variable
      id: timestamp
      run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
    
    - name: Print MY_DATE
      run: |
        echo MY_DATE: ${{ env.MY_DATE }}   
        echo TIMESTAMP: ${{ env.TIMESTAMP }} 

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ vars.CLIENT_ID_PRD }}
        tenant-id: ${{ vars.TENANT_ID_PRD }}
        subscription-id: ${{ vars.SUBSCRIPTION_ID_PRD }}

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta
      if: inputs.recover-delta
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_PRD }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_PRD }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta }}/${{env.BACKUP_SOURCE_FOLDER}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER}}' --recursive=true

    - name: AzCopy copy ${{env.BACKUP_ST_NAME}} to ${{env.DL_NAME}} delta-latest
      if: inputs.recover-delta-latest
      env:
        AZCOPY_SPA_APPLICATION_ID: ${{ vars.CLIENT_ID_PRD }}
        AZCOPY_TENANT_ID: ${{ vars.TENANT_ID_PRD }}
      run: | 
        azcopy_v10 copy 'https://${{env.BACKUP_ST_NAME}}.blob.core.windows.net/backup-datalake-delta-monthly/${{ inputs.date-delta-lates }}/${{env.BACKUP_SOURCE_FOLDER_2}}' 'https://${{env.DL_NAME}}.blob.core.windows.net/${{env.BACKUP_DEST_FOLDER_2}}' --recursive=true