name: "AzCopy OICD azcli"

on:
  workflow_dispatch:

env:
  ARM_USE_OIDC: true
  AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  AZCOPY_AUTO_LOGIN_TYPE: PSCRED

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: "dev"
    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
    steps:
      - name: "INFO"
        run: |
          echo AZURE_CLIENT_ID : ${{ env.AZURE_CLIENT_ID }}
          echo AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
          echo AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}

      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: "${{ env.AZURE_CLIENT_ID }}"
          subscription-id: "${{ env.AZURE_SUBSCRIPTION_ID }}"
          tenant-id: "${{ env.AZURE_TENANT_ID }}"
          enable-AzPSSession: true

      - name: "LS"
        run: |
          ls ..

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext
            $Date = (Get-Date -Format "yyyy-MM-dd")
            New-Item -ItemType File -Name 'my-file.txt' -Value "Hej"
            azcopy copy my-file.txt  https://stgithubprod01.blob.core.windows.net/abc/$Date/my-file.txt

      - name: Show env vars
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-ChildItem Env:
