name: 'Bicep Deploy'

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 3 * * *'

env:
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}  
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}
  TFSTATE_STORAGE :  ${{ vars.TFSTATE_STORAGE }}

permissions:
  contents: write
  pages: write
  id-token: write  

jobs:
  bicep_whatif:
    name: 'Bicep What-if'
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy: 
      fail-fast: false
      matrix:
          environment:
              - dev
              #- utv

    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/frontddor01

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
         client-id: '${{ env.ARM_CLIENT_ID }}'
         subscription-id: '${{ env.ARM_SUBSCRIPTION_ID }}'
         tenant-id: '${{ env.ARM_TENANT_ID }}'

    - name: Bicep What-if
      uses: Azure/cli@v2.0.0
      with:
        # Specify the script here
        inlineScript: |
            ls
        ## ./deploy.ps1 ${{ matrix.environment }} what-if
          


