name: 'Pipeline test'

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }} 
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}

permissions:
    id-token: write
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: 'dev'
        strategy: 
            fail-fast: false
            matrix: 
                environment:
                    - dev
        steps:
         - name: 'INFO'
           run: | 
                echo ARM_CLIENT_ID : ${{ env.ARM_CLIENT_ID }}
                echo ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
                echo ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
                
         - name: 'Az CLI login'
           uses: azure/login@v2
           with:
             client-id: '${{ env.ARM_CLIENT_ID }}'
             subscription-id: '${{ env.ARM_SUBSCRIPTION_ID }}'
             tenant-id: '${{ env.ARM_TENANT_ID }}'
      
         - name: 'Run az commands'
           run: |
               az account show
