name: 'Pipeline test'

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ vars.CLIENT_ID }} 
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }} 
  ARM_TENANT_ID: ${{ vars.TENANT_ID }}

permissions:
    id-token: write
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: 'dev'
        strategy: 
            fail-fast: false
            matrix:
                environment:
                    - dev
        steps:
         - name: 'INFO'
           run: | 
                echo ARM_CLIENT_ID : ${{ env.ARM_CLIENT_ID }}
                echo ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
                echo ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
                
         - name: 'Az CLI login'
           uses: azure/login@v1
           with:
             client-id: '4f689dd1-935e-453c-a5d2-4d3b9a3a5c76'  ##'${{ env.ARM_CLIENT_ID }}'
             subscription-id: '0dcc13b7-1a10-483e-95aa-fe7e71802e2e' #'${{ env.ARM_SUBSCRIPTION_ID }}'
             tenant-id: '7d5e28a9-aa48-43c6-a39a-3fc5167644de' #'${{ env.ARM_TENANT_ID }}'
      
#         - name: 'Run az commands'
#           run: |
#               az account show
#               az group list
  
         - name: 'INFO'
           run: | 
                echo ARM_CLIENT_ID : ${{ env.ARM_CLIENT_ID }}
                echo ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
                echo ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
