trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ci
      - iac
pool:
  vmImage: ubuntu-20.04

variables:
  azureSubscription-test: sub-almi-test-01
  azureSubscription-prod: sub-almi-prod-01
  workingDirectory: iac

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: iac
        displayName: Validate infrastructure
        steps:
          - task: AzurePowerShell@5
            displayName: test
            inputs:
              azureSubscription: $(azureSubscription-test)
              scriptPath: $(workingDirectory)/validate.ps1
              scriptArguments: test
              workingDirectory: $(workingDirectory)
              azurePowerShellVersion: latestVersion
              pwsh: true
          - task: AzurePowerShell@5
            displayName: prod
            inputs:
              azureSubscription: $(azureSubscription-prod)
              scriptPath: $(workingDirectory)/validate.ps1
              scriptArguments: prod
              workingDirectory: $(workingDirectory)
              azurePowerShellVersion: latestVersion
              pwsh: true

  - stage: test
    displayName: Deploy to test
    dependsOn: build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: iac
        displayName: Deploy infrastructure
        environment: test
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: $(azureSubscription-test)
                    scriptPath: $(workingDirectory)/deploy.ps1
                    scriptArguments: test
                    workingDirectory: $(workingDirectory)
                    azurePowerShellVersion: latestVersion
                    pwsh: true

  - stage: prod
    displayName: Deploy to prod
    dependsOn: test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: iac
        displayName: Deploy infrastructure
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  inputs:
                    azureSubscription: $(azureSubscription-prod)
                    scriptPath: $(workingDirectory)/deploy.ps1
                    scriptArguments: prod
                    workingDirectory: $(workingDirectory)
                    azurePowerShellVersion: latestVersion
                    pwsh: true
